[build]
    command = "npm run build"
    publish = "public"
    functions = "functions"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[[redirects]]
    from = "/store"
    to = "https://cottonbureau.com/people/daily-texas-country"
    status = 301

[[plugins]]
    package = "netlify-plugin-gatsby-cache"
