name: "🎧 tweet playlist"

on:
    schedule:
        # every friday @ 4pm
        - cron: "0 16 * * 5"

jobs:
    tweet:
        name: "🐦 tweet"
        runs-on: ubuntu-latest
        steps:
            - name: "🎣 webhook"
              uses: joelwmale/webhook-action@2.0.2
              with:
                  url: https://dailytexascountry.com/api/playlist
