name: "💿 tweet song"

on:
    schedule:
        # daily @ 8am
        # - cron: "0 8 * * *"
        # every 10 minutes
        - cron: "*/10 * * * *"

jobs:
    tweet:
        name: "🐦 tweet"
        runs-on: ubuntu-latest
        steps:
            - name: "🎣 webhook"
              uses: joelwmale/webhook-action@2.0.2
              with:
                  url: https://dailytexascountry.com/api/song
